# Generated by Django 5.0.1 on 2024-01-12 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('expired', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, max_length=300, verbose_name='Date and time of expiration')),
                ('qr_image', models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='alco_links', verbose_name='Date and time of expiration')),
            ],
            options={
                'verbose_name': 'Alco',
                'verbose_name_plural': 'Alcos',
                'ordering': ('expired', '-title'),
            },
        ),
    ]
