# Generated by Django 5.0.1 on 2024-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoinfo',
            name='qr_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='alco_links', verbose_name='Date and time of expiration'),
        ),
    ]
