# Generated by Django 5.0.1 on 2024-01-23 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_alcoinfo_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoinfo',
            name='qr_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='alco_links', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Date and time of expiration'),
        ),
    ]
